FROM centos:8
MAINTAINER kusari-k

RUN echo -e "\
[nginx-stable] \n\
name=nginx stable repo \n\
baseurl=http://nginx.org/packages/centos/\$releasever/\$basearch/ \n\
gpgcheck=1 \n\
enabled=1 \n\
gpgkey=https://nginx.org/keys/nginx_signing.key \n\
module_hotfixes=true \n\
\n\
[nginx-mainline] \n\
name=nginx mainline repo \n\
baseurl=http://nginx.org/packages/mainline/centos/\$releasever/\$basearch/ \n\
gpgcheck=1 \n\
enabled=0 \n\
gpgkey=https://nginx.org/keys/nginx_signing.key \n\
module_hotfixes=true" > /etc/yum.repos.d/nginx.repo

RUN sed -i -e "\$a fastestmirror=true" /etc/dnf/dnf.conf
RUN dnf update -y && \
	dnf install -y nginx rsyslog && \
	dnf clean all

COPY setting.log run-nginx.sh /usr/local/bin/
COPY letsencrypt /etc/letsencrypt

#/etc/nginx/nginx.conf
RUN sed  -i -e "/http\ /a \tserver_tokens off;" \
	-e "/keepalive/ s/65/5/" \
	-e "s/var\/log/log/g"
	-e "s/etc\/nginx/conf/g"

#RUN mkdir /etc/nginx/default_conf.d /etc/nginx/ssl && \
#	cp /etc/nginx/conf.d/default.conf /etc/nginx/default_conf.d/default.conf.old && \
#	cp -r /usr/share/nginx/html /etc/nginx/default_conf.d/ && \
#	openssl dhparam -out /etc/nginx/ssl/dhparam.pem 2048

RUN sed -i -e "/imjournal/ s/^/#/" \
	-e "s/off/on/" \
	-e "s/var\/log/log\/log/g" /etc/rsyslog.conf

RUN  chmod 755 /usr/local/bin/run-nginx.sh
ENTRYPOINT ["/usr/local/bin/run-nginx.sh"]
