version: '3.7'

services:
 webserver:
    build:
      context: .
    image: webserver
    container_name: webserver
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/:ro
      - /var/log/docker_log/webserver:/var/log/
      - /home/docker_home/webserver/conf.d/:/etc/nginx/user_conf.d/
      - /home/docker_home/webserver/nginx/:/usr/share/nginx/

networks:
  default:
    external:
      name: default_bridge
