FROM centos:8
MAINTAINER kusari-k

RUN sed -i -e "\$a fastestmirror=true" /etc/dnf/dnf.conf
RUN dnf install -y https://rpms.remirepo.net/enterprise/remi-release-8.rpm && \
	dnf update -y && \
	dnf install -y rsyslog @php:remi-8.0 && \
	dnf clean all

COPY setting.log run-php-fpm.sh /usr/local/bin/

RUN sed -i -e "s/var\/log/log/" /etc/php-fpm.conf

RUN sed -i -e "s/var\/log/log/" \
	-e "/^listen/ s/=.*/= 127.0.0.1:9000/g" /etc/php-fpm.d/www.conf

RUN sed -i -e "/imjournal/ s/^/#/" \
	-e "s/off/on/" \
	-e "s/var\/log/log/g" /etc/rsyslog.conf

RUN  chmod 755 /usr/local/bin/run-php-fpm.sh
ENTRYPOINT ["/usr/local/bin/run-php-fpm.sh"]
